-- ============================================================
-- CORTEX GESTAO - 13: IMPORTAR O GUIA DE SALAS ANTIGO
-- Rodar no SQL Editor do projeto CORTEX-GESTAO
-- (vznjdgofvjbyivqkygvx) - DEPOIS do 12_salas.sql.
-- Pode rodar mais de uma vez: nao duplica salas nem grade.
--
-- O que faz:
--   1. Cria as 42 salas do sistema antigo (EQ1 e EQ2, com
--      andar, especialidade e cor herdadas do croqui).
--   2. Preenche a grade da semana (492 celulas): profissionais
--      casados pelo nome com os colaboradores (sem acento e por
--      inicio de nome, se unico); quem nao casar entra como
--      ROTULO com o mesmo nome - a grade fica identica ao croqui
--      e voce troca o rotulo pela ficha na celula quando quiser.
--      Celulas '#X' do antigo viram 'Indisponivel'.
--   3. Relatorio final: quem casou e quem virou rotulo.
-- ============================================================

drop table if exists imp_salas_res;
create temp table imp_salas_res (nome text primary key, colaborador_id uuid, situacao text);

create or replace function pg_temp.norm(t text) returns text
language sql immutable as $$
  select trim(regexp_replace(
    translate(lower(coalesce(t, '')),
      'áàâãäéèêëíìîïóòôõöúùûüçñ',
      'aaaaaeeeeiiiiooooouuuucn'),
    '\s+', ' ', 'g'))
$$;

do $$
declare
  r record;
  v_sala uuid;
  v_colab uuid;
  v_qtd int;
  n_salas_novas int := 0;
  n_salas_ja int := 0;
  n_oc int := 0;
  n_oc_ja int := 0;
begin
  -- ---------- 1) SALAS ----------
  for r in
    select * from (values
      ('EQ1', '4', '1º andar', 'Psicologia', '#f9bed7'),
      ('EQ1', '3', '1º andar', 'Psicologia', '#fa8dfc'),
      ('EQ1', '2', '1º andar', 'Psicologia', '#f856fb'),
      ('EQ1', '1', '1º andar', 'Psicologia', '#ffdd94'),
      ('EQ1', '5', '1º andar', 'Psicologia', '#74a4d8'),
      ('EQ1', '6', '1º andar', 'Psicologia', '#b4d8fe'),
      ('EQ1', '7', '1º andar', 'Neuropsicologia', '#b4fec6'),
      ('EQ1', '4', '2º andar', 'Neuropsicologia', '#b4fec6'),
      ('EQ1', '3', '2º andar', 'Neuropsicologia', '#b4fec6'),
      ('EQ1', '2', '2º andar', 'Neuropsicologia', '#b4fec6'),
      ('EQ1', '1', '2º andar', 'Neuropsicologia', '#b4fec6'),
      ('EQ1', '5', '2º andar', 'Psicologia', '#74a4d8'),
      ('EQ1', '6', '2º andar', 'Médico', '#3898ff'),
      ('EQ1', '7', '2º andar', 'Médico', '#62bafe'),
      ('EQ1', '7', '3º andar', null, null),
      ('EQ1', '6', '3º andar', 'Psicologia', '#fe8686'),
      ('EQ1', '5', '3º andar', 'Psicologia', '#feb4b4'),
      ('EQ1', '4', '3º andar', null, null),
      ('EQ1', '1', '3º andar', 'Médico', '#a5d0fd'),
      ('EQ1', '2', '3º andar', 'Neuropsicologia', '#b4fec6'),
      ('EQ1', '3', '3º andar', 'Neuropsicologia', '#58fe92'),
      ('EQ2', '11', '1º andar', 'Psicopedagogia', '#E08A3C'),
      ('EQ2', '12', '1º andar', 'Psicopedagogia', '#E08A3C'),
      ('EQ2', '13', '1º andar', 'Fonoaudiologia', '#2E9E78'),
      ('EQ2', '14', '1º andar', 'Fonoaudiologia', '#2E9E78'),
      ('EQ2', '15', '1º andar', 'Fonoaudiologia', '#2E9E78'),
      ('EQ2', '16', '1º andar', 'Psicologia Adolescência/Infantil', '#2E75B6'),
      ('EQ2', '17', '1º andar', 'ABA', '#C0526E'),
      ('EQ2', '18', '1º andar', 'ABA', '#C0526E'),
      ('EQ2', '19', '1º andar', 'ABA', '#C0526E'),
      ('EQ2', '20', '1º andar', 'ABA', '#C0526E'),
      ('EQ2', '21', '1º andar', 'ABA', '#C0526E'),
      ('EQ2', '22', '1º andar', 'ABA', '#C0526E'),
      ('EQ2', '23', '1º andar', 'ABA', '#C0526E'),
      ('EQ2', '24', '1º andar', 'ABA', '#C0526E'),
      ('EQ2', '01', 'Térreo', 'Psicomotricidade', '#5B6BB5'),
      ('EQ2', '02', 'Térreo', null, null),
      ('EQ2', '03', 'Térreo', null, null),
      ('EQ2', '04', 'Térreo', 'Musicoterapia', '#8E6FB5'),
      ('EQ2', '05', 'Térreo', null, null),
      ('EQ2', '06', 'Térreo', null, null),
      ('EQ2', '07', 'Térreo', 'Terapia Ocupacional', '#0E8F8F')
    ) as v(unidade, numero, andar, especialidade, cor)
  loop
    select id into v_sala from public.salas s
     where s.unidade = r.unidade and lower(s.numero) = lower(r.numero)
       and coalesce(s.andar, '') = r.andar;
    if v_sala is null then
      insert into public.salas (numero, unidade, andar, especialidade, cor)
      values (r.numero, r.unidade, r.andar, r.especialidade, r.cor);
      n_salas_novas := n_salas_novas + 1;
    else
      n_salas_ja := n_salas_ja + 1;
    end if;
  end loop;

  -- ---------- 2) CASAMENTO DOS NOMES ----------
  for r in
    select * from (values
      ('Aline'),
      ('Ana Maria'),
      ('Bruno'),
      ('Daiane'),
      ('Eduardo'),
      ('Emilly'),
      ('Francisca'),
      ('Gabriela'),
      ('Hugo'),
      ('Jeniffer'),
      ('Jéssica'),
      ('Karolina'),
      ('Kênia'),
      ('Lara'),
      ('Laís'),
      ('Luan'),
      ('Lucas'),
      ('Mara'),
      ('Mariana'),
      ('Mayumi'),
      ('Michelle'),
      ('Mona'),
      ('Natália'),
      ('Priscila'),
      ('Pâmela'),
      ('Rosana'),
      ('Sandra'),
      ('Sílvia'),
      ('Taís'),
      ('Terapia ABA'),
      ('Vitor'),
      ('Vitória'),
      ('Wellington'),
      ('Wessilon'),
      ('Yuri')
    ) as v(nome)
  loop
    v_colab := null;
    select id into v_colab from public.colaboradores
     where status <> 'desligado' and pg_temp.norm(nome) = pg_temp.norm(r.nome);
    if v_colab is null then
      select count(*) into v_qtd from public.colaboradores
       where status <> 'desligado' and pg_temp.norm(nome) like pg_temp.norm(r.nome) || ' %';
      if v_qtd = 1 then
        select id into v_colab from public.colaboradores
         where status <> 'desligado' and pg_temp.norm(nome) like pg_temp.norm(r.nome) || ' %';
      end if;
    end if;
    insert into imp_salas_res values (r.nome, v_colab,
      case when v_colab is null then 'vira RÓTULO (ajuste na célula quando quiser)' else 'casado' end);
  end loop;

  -- ---------- 3) GRADE ----------
  for r in
    select * from (values
      ('EQ1', '4', '1º andar', 1, 1, 'Laís'),
      ('EQ1', '4', '1º andar', 1, 2, 'Laís'),
      ('EQ1', '4', '1º andar', 1, 3, 'Laís'),
      ('EQ1', '4', '1º andar', 2, 1, 'Laís'),
      ('EQ1', '4', '1º andar', 2, 2, 'Laís'),
      ('EQ1', '4', '1º andar', 2, 3, 'Laís'),
      ('EQ1', '4', '1º andar', 3, 1, 'Laís'),
      ('EQ1', '4', '1º andar', 3, 2, 'Laís'),
      ('EQ1', '4', '1º andar', 3, 3, 'Laís'),
      ('EQ1', '4', '1º andar', 4, 1, 'Laís'),
      ('EQ1', '4', '1º andar', 4, 2, 'Laís'),
      ('EQ1', '4', '1º andar', 4, 3, 'Laís'),
      ('EQ1', '4', '1º andar', 5, 1, 'Laís'),
      ('EQ1', '4', '1º andar', 5, 2, 'Laís'),
      ('EQ1', '4', '1º andar', 5, 3, 'Laís'),
      ('EQ1', '4', '1º andar', 6, 2, null),
      ('EQ1', '4', '1º andar', 6, 3, null),
      ('EQ1', '3', '1º andar', 1, 1, 'Gabriela'),
      ('EQ1', '3', '1º andar', 1, 2, 'Gabriela'),
      ('EQ1', '3', '1º andar', 1, 3, 'Gabriela'),
      ('EQ1', '3', '1º andar', 2, 1, 'Gabriela'),
      ('EQ1', '3', '1º andar', 2, 2, 'Gabriela'),
      ('EQ1', '3', '1º andar', 2, 3, 'Gabriela'),
      ('EQ1', '3', '1º andar', 3, 1, 'Gabriela'),
      ('EQ1', '3', '1º andar', 3, 2, 'Gabriela'),
      ('EQ1', '3', '1º andar', 3, 3, 'Gabriela'),
      ('EQ1', '3', '1º andar', 4, 1, 'Gabriela'),
      ('EQ1', '3', '1º andar', 4, 2, 'Gabriela'),
      ('EQ1', '3', '1º andar', 4, 3, 'Gabriela'),
      ('EQ1', '3', '1º andar', 5, 1, 'Gabriela'),
      ('EQ1', '3', '1º andar', 5, 2, 'Gabriela'),
      ('EQ1', '3', '1º andar', 5, 3, 'Gabriela'),
      ('EQ1', '3', '1º andar', 6, 2, null),
      ('EQ1', '3', '1º andar', 6, 3, null),
      ('EQ1', '2', '1º andar', 1, 2, 'Rosana'),
      ('EQ1', '2', '1º andar', 1, 3, 'Rosana'),
      ('EQ1', '2', '1º andar', 2, 1, 'Rosana'),
      ('EQ1', '2', '1º andar', 2, 2, 'Rosana'),
      ('EQ1', '2', '1º andar', 2, 3, 'Rosana'),
      ('EQ1', '2', '1º andar', 3, 1, 'Jeniffer'),
      ('EQ1', '2', '1º andar', 3, 2, 'Rosana'),
      ('EQ1', '2', '1º andar', 3, 3, 'Rosana'),
      ('EQ1', '2', '1º andar', 4, 1, 'Rosana'),
      ('EQ1', '2', '1º andar', 4, 2, 'Rosana'),
      ('EQ1', '2', '1º andar', 4, 3, 'Rosana'),
      ('EQ1', '2', '1º andar', 5, 1, 'Jeniffer'),
      ('EQ1', '2', '1º andar', 5, 2, 'Jeniffer'),
      ('EQ1', '2', '1º andar', 5, 3, 'Jeniffer'),
      ('EQ1', '2', '1º andar', 6, 2, null),
      ('EQ1', '2', '1º andar', 6, 3, null),
      ('EQ1', '1', '1º andar', 1, 1, 'Vitória'),
      ('EQ1', '1', '1º andar', 1, 2, 'Vitória'),
      ('EQ1', '1', '1º andar', 1, 3, 'Vitória'),
      ('EQ1', '1', '1º andar', 2, 1, 'Vitória'),
      ('EQ1', '1', '1º andar', 2, 2, 'Vitória'),
      ('EQ1', '1', '1º andar', 3, 1, 'Vitória'),
      ('EQ1', '1', '1º andar', 3, 2, 'Vitória'),
      ('EQ1', '1', '1º andar', 3, 3, 'Vitória'),
      ('EQ1', '1', '1º andar', 4, 1, 'Vitória'),
      ('EQ1', '1', '1º andar', 4, 2, 'Vitória'),
      ('EQ1', '1', '1º andar', 4, 3, 'Vitória'),
      ('EQ1', '1', '1º andar', 6, 2, null),
      ('EQ1', '1', '1º andar', 6, 3, null),
      ('EQ1', '5', '1º andar', 1, 1, 'Yuri'),
      ('EQ1', '5', '1º andar', 1, 2, 'Michelle'),
      ('EQ1', '5', '1º andar', 2, 1, 'Yuri'),
      ('EQ1', '5', '1º andar', 2, 2, 'Michelle'),
      ('EQ1', '5', '1º andar', 3, 1, 'Yuri'),
      ('EQ1', '5', '1º andar', 3, 2, 'Michelle'),
      ('EQ1', '5', '1º andar', 4, 1, 'Yuri'),
      ('EQ1', '5', '1º andar', 4, 2, 'Michelle'),
      ('EQ1', '5', '1º andar', 5, 1, 'Yuri'),
      ('EQ1', '5', '1º andar', 5, 2, 'Michelle'),
      ('EQ1', '5', '1º andar', 6, 2, null),
      ('EQ1', '5', '1º andar', 6, 3, null),
      ('EQ1', '6', '1º andar', 1, 2, 'Mara'),
      ('EQ1', '6', '1º andar', 1, 3, 'Mara'),
      ('EQ1', '6', '1º andar', 2, 2, 'Mara'),
      ('EQ1', '6', '1º andar', 2, 3, 'Mara'),
      ('EQ1', '6', '1º andar', 3, 1, 'Mara'),
      ('EQ1', '6', '1º andar', 4, 2, 'Mara'),
      ('EQ1', '6', '1º andar', 4, 3, 'Mara'),
      ('EQ1', '6', '1º andar', 5, 1, 'Mara'),
      ('EQ1', '6', '1º andar', 6, 2, null),
      ('EQ1', '6', '1º andar', 6, 3, null),
      ('EQ1', '7', '1º andar', 1, 1, 'Mariana'),
      ('EQ1', '7', '1º andar', 2, 1, 'Mariana'),
      ('EQ1', '7', '1º andar', 3, 1, 'Mariana'),
      ('EQ1', '7', '1º andar', 3, 2, 'Jeniffer'),
      ('EQ1', '7', '1º andar', 3, 3, 'Jeniffer'),
      ('EQ1', '7', '1º andar', 4, 1, 'Mariana'),
      ('EQ1', '7', '1º andar', 5, 1, 'Mariana'),
      ('EQ1', '7', '1º andar', 6, 2, null),
      ('EQ1', '7', '1º andar', 6, 3, null),
      ('EQ1', '4', '2º andar', 1, 1, 'Pâmela'),
      ('EQ1', '4', '2º andar', 1, 2, 'Pâmela'),
      ('EQ1', '4', '2º andar', 2, 1, 'Pâmela'),
      ('EQ1', '4', '2º andar', 2, 2, 'Pâmela'),
      ('EQ1', '4', '2º andar', 3, 1, 'Pâmela'),
      ('EQ1', '4', '2º andar', 3, 2, 'Pâmela'),
      ('EQ1', '4', '2º andar', 4, 1, 'Pâmela'),
      ('EQ1', '4', '2º andar', 4, 2, 'Pâmela'),
      ('EQ1', '4', '2º andar', 5, 1, 'Pâmela'),
      ('EQ1', '4', '2º andar', 5, 2, 'Pâmela'),
      ('EQ1', '4', '2º andar', 6, 2, null),
      ('EQ1', '4', '2º andar', 6, 3, null),
      ('EQ1', '3', '2º andar', 1, 1, 'Emilly'),
      ('EQ1', '3', '2º andar', 1, 2, 'Emilly'),
      ('EQ1', '3', '2º andar', 2, 1, 'Emilly'),
      ('EQ1', '3', '2º andar', 2, 2, 'Emilly'),
      ('EQ1', '3', '2º andar', 3, 1, 'Emilly'),
      ('EQ1', '3', '2º andar', 3, 2, 'Emilly'),
      ('EQ1', '3', '2º andar', 4, 1, 'Emilly'),
      ('EQ1', '3', '2º andar', 4, 2, 'Emilly'),
      ('EQ1', '3', '2º andar', 5, 1, 'Emilly'),
      ('EQ1', '3', '2º andar', 5, 2, 'Emilly'),
      ('EQ1', '3', '2º andar', 6, 2, null),
      ('EQ1', '3', '2º andar', 6, 3, null),
      ('EQ1', '2', '2º andar', 1, 1, 'Taís'),
      ('EQ1', '2', '2º andar', 1, 2, 'Taís'),
      ('EQ1', '2', '2º andar', 2, 1, 'Taís'),
      ('EQ1', '2', '2º andar', 2, 2, 'Taís'),
      ('EQ1', '2', '2º andar', 3, 1, 'Taís'),
      ('EQ1', '2', '2º andar', 3, 2, 'Taís'),
      ('EQ1', '2', '2º andar', 4, 1, 'Taís'),
      ('EQ1', '2', '2º andar', 4, 2, 'Taís'),
      ('EQ1', '2', '2º andar', 5, 1, 'Taís'),
      ('EQ1', '2', '2º andar', 5, 2, 'Taís'),
      ('EQ1', '2', '2º andar', 6, 2, null),
      ('EQ1', '2', '2º andar', 6, 3, null),
      ('EQ1', '1', '2º andar', 1, 2, 'Karolina'),
      ('EQ1', '1', '2º andar', 2, 1, 'Karolina'),
      ('EQ1', '1', '2º andar', 3, 1, 'Karolina'),
      ('EQ1', '1', '2º andar', 3, 2, 'Karolina'),
      ('EQ1', '1', '2º andar', 4, 1, 'Karolina'),
      ('EQ1', '1', '2º andar', 4, 2, 'Karolina'),
      ('EQ1', '1', '2º andar', 5, 1, 'Karolina'),
      ('EQ1', '1', '2º andar', 5, 2, 'Karolina'),
      ('EQ1', '1', '2º andar', 6, 2, null),
      ('EQ1', '1', '2º andar', 6, 3, null),
      ('EQ1', '5', '2º andar', 1, 2, 'Yuri'),
      ('EQ1', '5', '2º andar', 2, 1, 'Vitor'),
      ('EQ1', '5', '2º andar', 2, 2, 'Yuri'),
      ('EQ1', '5', '2º andar', 3, 2, 'Yuri'),
      ('EQ1', '5', '2º andar', 4, 2, 'Yuri'),
      ('EQ1', '5', '2º andar', 5, 1, 'Vitor'),
      ('EQ1', '5', '2º andar', 5, 2, 'Yuri'),
      ('EQ1', '5', '2º andar', 6, 2, null),
      ('EQ1', '5', '2º andar', 6, 3, null),
      ('EQ1', '6', '2º andar', 1, 2, 'Wellington'),
      ('EQ1', '6', '2º andar', 1, 3, 'Wellington'),
      ('EQ1', '6', '2º andar', 2, 2, 'Lucas'),
      ('EQ1', '6', '2º andar', 2, 3, 'Lucas'),
      ('EQ1', '6', '2º andar', 3, 1, 'Lucas'),
      ('EQ1', '6', '2º andar', 3, 2, 'Wellington'),
      ('EQ1', '6', '2º andar', 3, 3, 'Wellington'),
      ('EQ1', '6', '2º andar', 5, 1, 'Wellington'),
      ('EQ1', '6', '2º andar', 5, 2, 'Wellington'),
      ('EQ1', '6', '2º andar', 5, 3, 'Wellington'),
      ('EQ1', '6', '2º andar', 6, 2, null),
      ('EQ1', '6', '2º andar', 6, 3, null),
      ('EQ1', '7', '2º andar', 1, 1, 'Luan'),
      ('EQ1', '7', '2º andar', 1, 2, 'Luan'),
      ('EQ1', '7', '2º andar', 1, 3, 'Luan'),
      ('EQ1', '7', '2º andar', 2, 1, 'Priscila'),
      ('EQ1', '7', '2º andar', 4, 1, 'Luan'),
      ('EQ1', '7', '2º andar', 4, 2, 'Luan'),
      ('EQ1', '7', '2º andar', 4, 3, 'Luan'),
      ('EQ1', '7', '2º andar', 6, 2, null),
      ('EQ1', '7', '2º andar', 6, 3, null),
      ('EQ1', '7', '3º andar', 6, 2, null),
      ('EQ1', '7', '3º andar', 6, 3, null),
      ('EQ1', '6', '3º andar', 1, 1, 'Francisca'),
      ('EQ1', '6', '3º andar', 1, 2, 'Kênia'),
      ('EQ1', '6', '3º andar', 1, 3, 'Kênia'),
      ('EQ1', '6', '3º andar', 2, 1, 'Francisca'),
      ('EQ1', '6', '3º andar', 2, 2, 'Kênia'),
      ('EQ1', '6', '3º andar', 2, 3, 'Kênia'),
      ('EQ1', '6', '3º andar', 3, 1, 'Francisca'),
      ('EQ1', '6', '3º andar', 3, 2, 'Kênia'),
      ('EQ1', '6', '3º andar', 3, 3, 'Kênia'),
      ('EQ1', '6', '3º andar', 4, 1, 'Francisca'),
      ('EQ1', '6', '3º andar', 4, 2, 'Kênia'),
      ('EQ1', '6', '3º andar', 4, 3, 'Kênia'),
      ('EQ1', '6', '3º andar', 5, 1, 'Francisca'),
      ('EQ1', '6', '3º andar', 5, 2, 'Kênia'),
      ('EQ1', '6', '3º andar', 5, 3, 'Kênia'),
      ('EQ1', '6', '3º andar', 6, 2, null),
      ('EQ1', '6', '3º andar', 6, 3, null),
      ('EQ1', '5', '3º andar', 1, 2, 'Jéssica'),
      ('EQ1', '5', '3º andar', 1, 3, 'Jéssica'),
      ('EQ1', '5', '3º andar', 2, 2, 'Jéssica'),
      ('EQ1', '5', '3º andar', 2, 3, 'Jéssica'),
      ('EQ1', '5', '3º andar', 3, 2, 'Jéssica'),
      ('EQ1', '5', '3º andar', 3, 3, 'Jéssica'),
      ('EQ1', '5', '3º andar', 4, 2, 'Jéssica'),
      ('EQ1', '5', '3º andar', 4, 3, 'Jéssica'),
      ('EQ1', '5', '3º andar', 5, 2, 'Jéssica'),
      ('EQ1', '5', '3º andar', 5, 3, 'Jéssica'),
      ('EQ1', '5', '3º andar', 6, 1, 'Jéssica'),
      ('EQ1', '5', '3º andar', 6, 2, null),
      ('EQ1', '5', '3º andar', 6, 3, null),
      ('EQ1', '4', '3º andar', 6, 2, null),
      ('EQ1', '4', '3º andar', 6, 3, null),
      ('EQ1', '1', '3º andar', 1, 1, 'Bruno'),
      ('EQ1', '1', '3º andar', 1, 3, 'Sílvia'),
      ('EQ1', '1', '3º andar', 2, 1, 'Bruno'),
      ('EQ1', '1', '3º andar', 2, 3, 'Sílvia'),
      ('EQ1', '1', '3º andar', 3, 1, 'Bruno'),
      ('EQ1', '1', '3º andar', 4, 1, 'Bruno'),
      ('EQ1', '1', '3º andar', 4, 3, 'Sílvia'),
      ('EQ1', '1', '3º andar', 5, 1, 'Bruno'),
      ('EQ1', '1', '3º andar', 6, 1, 'Sílvia'),
      ('EQ1', '1', '3º andar', 6, 2, null),
      ('EQ1', '1', '3º andar', 6, 3, null),
      ('EQ1', '2', '3º andar', 1, 1, 'Natália'),
      ('EQ1', '2', '3º andar', 2, 2, 'Natália'),
      ('EQ1', '2', '3º andar', 2, 3, 'Natália'),
      ('EQ1', '2', '3º andar', 3, 2, 'Natália'),
      ('EQ1', '2', '3º andar', 3, 3, 'Natália'),
      ('EQ1', '2', '3º andar', 4, 2, 'Natália'),
      ('EQ1', '2', '3º andar', 4, 3, 'Natália'),
      ('EQ1', '2', '3º andar', 5, 1, 'Natália'),
      ('EQ1', '2', '3º andar', 5, 2, 'Natália'),
      ('EQ1', '2', '3º andar', 6, 2, null),
      ('EQ1', '2', '3º andar', 6, 3, null),
      ('EQ1', '3', '3º andar', 1, 1, 'Wessilon'),
      ('EQ1', '3', '3º andar', 1, 2, 'Wessilon'),
      ('EQ1', '3', '3º andar', 1, 3, 'Wessilon'),
      ('EQ1', '3', '3º andar', 2, 1, 'Wessilon'),
      ('EQ1', '3', '3º andar', 2, 2, 'Wessilon'),
      ('EQ1', '3', '3º andar', 2, 3, 'Wessilon'),
      ('EQ1', '3', '3º andar', 3, 1, 'Wessilon'),
      ('EQ1', '3', '3º andar', 3, 2, 'Wessilon'),
      ('EQ1', '3', '3º andar', 3, 3, 'Wessilon'),
      ('EQ1', '3', '3º andar', 4, 1, 'Wessilon'),
      ('EQ1', '3', '3º andar', 4, 2, 'Wessilon'),
      ('EQ1', '3', '3º andar', 5, 1, 'Wessilon'),
      ('EQ1', '3', '3º andar', 6, 2, null),
      ('EQ1', '3', '3º andar', 6, 3, null),
      ('EQ2', '11', '1º andar', 1, 1, 'Ana Maria'),
      ('EQ2', '11', '1º andar', 1, 2, 'Ana Maria'),
      ('EQ2', '11', '1º andar', 2, 1, 'Ana Maria'),
      ('EQ2', '11', '1º andar', 2, 2, 'Ana Maria'),
      ('EQ2', '11', '1º andar', 3, 1, 'Ana Maria'),
      ('EQ2', '11', '1º andar', 3, 2, 'Ana Maria'),
      ('EQ2', '11', '1º andar', 4, 1, 'Ana Maria'),
      ('EQ2', '11', '1º andar', 4, 2, 'Ana Maria'),
      ('EQ2', '11', '1º andar', 5, 1, 'Ana Maria'),
      ('EQ2', '11', '1º andar', 5, 2, 'Ana Maria'),
      ('EQ2', '11', '1º andar', 6, 2, null),
      ('EQ2', '11', '1º andar', 6, 3, null),
      ('EQ2', '12', '1º andar', 1, 1, 'Daiane'),
      ('EQ2', '12', '1º andar', 2, 1, 'Daiane'),
      ('EQ2', '12', '1º andar', 3, 1, 'Daiane'),
      ('EQ2', '12', '1º andar', 4, 1, 'Daiane'),
      ('EQ2', '12', '1º andar', 5, 1, 'Daiane'),
      ('EQ2', '12', '1º andar', 6, 2, null),
      ('EQ2', '12', '1º andar', 6, 3, null),
      ('EQ2', '13', '1º andar', 1, 1, 'Hugo'),
      ('EQ2', '13', '1º andar', 1, 2, 'Hugo'),
      ('EQ2', '13', '1º andar', 1, 3, 'Hugo'),
      ('EQ2', '13', '1º andar', 2, 1, 'Hugo'),
      ('EQ2', '13', '1º andar', 2, 2, 'Hugo'),
      ('EQ2', '13', '1º andar', 2, 3, 'Hugo'),
      ('EQ2', '13', '1º andar', 3, 1, 'Hugo'),
      ('EQ2', '13', '1º andar', 3, 2, 'Hugo'),
      ('EQ2', '13', '1º andar', 3, 3, 'Hugo'),
      ('EQ2', '13', '1º andar', 4, 1, 'Hugo'),
      ('EQ2', '13', '1º andar', 4, 2, 'Hugo'),
      ('EQ2', '13', '1º andar', 4, 3, 'Hugo'),
      ('EQ2', '13', '1º andar', 5, 1, 'Hugo'),
      ('EQ2', '13', '1º andar', 5, 2, 'Hugo'),
      ('EQ2', '13', '1º andar', 5, 3, 'Hugo'),
      ('EQ2', '13', '1º andar', 6, 2, null),
      ('EQ2', '13', '1º andar', 6, 3, null),
      ('EQ2', '14', '1º andar', 1, 1, 'Aline'),
      ('EQ2', '14', '1º andar', 1, 2, 'Aline'),
      ('EQ2', '14', '1º andar', 1, 3, 'Aline'),
      ('EQ2', '14', '1º andar', 2, 1, 'Aline'),
      ('EQ2', '14', '1º andar', 2, 2, 'Aline'),
      ('EQ2', '14', '1º andar', 2, 3, 'Aline'),
      ('EQ2', '14', '1º andar', 3, 1, 'Aline'),
      ('EQ2', '14', '1º andar', 3, 2, 'Aline'),
      ('EQ2', '14', '1º andar', 3, 3, 'Aline'),
      ('EQ2', '14', '1º andar', 4, 1, 'Aline'),
      ('EQ2', '14', '1º andar', 4, 2, 'Aline'),
      ('EQ2', '14', '1º andar', 4, 3, 'Aline'),
      ('EQ2', '14', '1º andar', 5, 1, 'Aline'),
      ('EQ2', '14', '1º andar', 5, 2, 'Aline'),
      ('EQ2', '14', '1º andar', 5, 3, 'Aline'),
      ('EQ2', '14', '1º andar', 6, 2, null),
      ('EQ2', '14', '1º andar', 6, 3, null),
      ('EQ2', '15', '1º andar', 1, 1, 'Lara'),
      ('EQ2', '15', '1º andar', 1, 2, 'Lara'),
      ('EQ2', '15', '1º andar', 1, 3, 'Lara'),
      ('EQ2', '15', '1º andar', 3, 2, 'Lara'),
      ('EQ2', '15', '1º andar', 3, 3, 'Lara'),
      ('EQ2', '15', '1º andar', 5, 1, 'Lara'),
      ('EQ2', '15', '1º andar', 6, 2, null),
      ('EQ2', '15', '1º andar', 6, 3, null),
      ('EQ2', '16', '1º andar', 1, 1, 'Mayumi'),
      ('EQ2', '16', '1º andar', 1, 2, 'Mayumi'),
      ('EQ2', '16', '1º andar', 1, 3, 'Mayumi'),
      ('EQ2', '16', '1º andar', 2, 1, 'Mayumi'),
      ('EQ2', '16', '1º andar', 2, 2, 'Mayumi'),
      ('EQ2', '16', '1º andar', 2, 3, 'Mayumi'),
      ('EQ2', '16', '1º andar', 3, 1, 'Mayumi'),
      ('EQ2', '16', '1º andar', 3, 2, 'Mayumi'),
      ('EQ2', '16', '1º andar', 3, 3, 'Mayumi'),
      ('EQ2', '16', '1º andar', 4, 1, 'Mayumi'),
      ('EQ2', '16', '1º andar', 4, 2, 'Mayumi'),
      ('EQ2', '16', '1º andar', 4, 3, 'Mayumi'),
      ('EQ2', '16', '1º andar', 5, 1, 'Mayumi'),
      ('EQ2', '16', '1º andar', 5, 2, 'Mayumi'),
      ('EQ2', '16', '1º andar', 5, 3, 'Mayumi'),
      ('EQ2', '16', '1º andar', 6, 2, null),
      ('EQ2', '16', '1º andar', 6, 3, null),
      ('EQ2', '17', '1º andar', 1, 1, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 1, 2, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 1, 3, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 2, 1, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 2, 2, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 2, 3, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 3, 1, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 3, 2, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 3, 3, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 4, 1, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 4, 2, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 4, 3, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 5, 1, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 5, 2, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 5, 3, 'Terapia ABA'),
      ('EQ2', '17', '1º andar', 6, 2, null),
      ('EQ2', '17', '1º andar', 6, 3, null),
      ('EQ2', '18', '1º andar', 1, 1, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 1, 2, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 1, 3, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 2, 1, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 2, 2, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 2, 3, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 3, 1, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 3, 2, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 3, 3, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 4, 1, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 4, 2, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 4, 3, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 5, 1, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 5, 2, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 5, 3, 'Terapia ABA'),
      ('EQ2', '18', '1º andar', 6, 2, null),
      ('EQ2', '18', '1º andar', 6, 3, null),
      ('EQ2', '19', '1º andar', 1, 1, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 1, 2, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 1, 3, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 2, 1, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 2, 2, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 2, 3, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 3, 1, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 3, 2, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 3, 3, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 4, 1, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 4, 2, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 4, 3, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 5, 1, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 5, 2, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 5, 3, 'Terapia ABA'),
      ('EQ2', '19', '1º andar', 6, 2, null),
      ('EQ2', '19', '1º andar', 6, 3, null),
      ('EQ2', '20', '1º andar', 1, 1, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 1, 2, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 1, 3, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 2, 1, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 2, 2, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 2, 3, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 3, 1, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 3, 2, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 3, 3, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 4, 1, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 4, 2, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 4, 3, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 5, 1, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 5, 2, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 5, 3, 'Terapia ABA'),
      ('EQ2', '20', '1º andar', 6, 2, null),
      ('EQ2', '20', '1º andar', 6, 3, null),
      ('EQ2', '21', '1º andar', 1, 1, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 1, 2, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 1, 3, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 2, 1, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 2, 2, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 2, 3, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 3, 1, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 3, 2, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 3, 3, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 4, 1, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 4, 2, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 4, 3, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 5, 1, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 5, 2, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 5, 3, 'Terapia ABA'),
      ('EQ2', '21', '1º andar', 6, 2, null),
      ('EQ2', '21', '1º andar', 6, 3, null),
      ('EQ2', '22', '1º andar', 1, 1, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 1, 2, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 1, 3, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 2, 1, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 2, 2, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 2, 3, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 3, 1, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 3, 2, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 3, 3, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 4, 1, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 4, 2, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 4, 3, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 5, 1, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 5, 2, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 5, 3, 'Terapia ABA'),
      ('EQ2', '22', '1º andar', 6, 2, null),
      ('EQ2', '22', '1º andar', 6, 3, null),
      ('EQ2', '23', '1º andar', 1, 1, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 1, 2, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 1, 3, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 2, 1, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 2, 2, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 2, 3, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 3, 1, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 3, 2, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 3, 3, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 4, 1, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 4, 2, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 4, 3, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 5, 1, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 5, 2, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 5, 3, 'Terapia ABA'),
      ('EQ2', '23', '1º andar', 6, 2, null),
      ('EQ2', '23', '1º andar', 6, 3, null),
      ('EQ2', '24', '1º andar', 1, 1, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 1, 2, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 1, 3, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 2, 1, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 2, 2, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 2, 3, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 3, 1, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 3, 2, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 3, 3, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 4, 1, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 4, 2, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 4, 3, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 5, 1, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 5, 2, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 5, 3, 'Terapia ABA'),
      ('EQ2', '24', '1º andar', 6, 2, null),
      ('EQ2', '24', '1º andar', 6, 3, null),
      ('EQ2', '01', 'Térreo', 1, 1, 'Mona'),
      ('EQ2', '01', 'Térreo', 1, 2, 'Mona'),
      ('EQ2', '01', 'Térreo', 1, 3, 'Mona'),
      ('EQ2', '01', 'Térreo', 2, 1, 'Mona'),
      ('EQ2', '01', 'Térreo', 2, 2, 'Mona'),
      ('EQ2', '01', 'Térreo', 2, 3, 'Mona'),
      ('EQ2', '01', 'Térreo', 3, 1, 'Mona'),
      ('EQ2', '01', 'Térreo', 3, 2, 'Mona'),
      ('EQ2', '01', 'Térreo', 3, 3, 'Mona'),
      ('EQ2', '01', 'Térreo', 5, 1, 'Mona'),
      ('EQ2', '01', 'Térreo', 6, 2, null),
      ('EQ2', '01', 'Térreo', 6, 3, null),
      ('EQ2', '02', 'Térreo', 6, 2, null),
      ('EQ2', '02', 'Térreo', 6, 3, null),
      ('EQ2', '03', 'Térreo', 6, 2, null),
      ('EQ2', '03', 'Térreo', 6, 3, null),
      ('EQ2', '04', 'Térreo', 2, 2, 'Sandra'),
      ('EQ2', '04', 'Térreo', 2, 3, 'Sandra'),
      ('EQ2', '04', 'Térreo', 6, 2, null),
      ('EQ2', '04', 'Térreo', 6, 3, null),
      ('EQ2', '05', 'Térreo', 6, 2, null),
      ('EQ2', '05', 'Térreo', 6, 3, null),
      ('EQ2', '06', 'Térreo', 6, 2, null),
      ('EQ2', '06', 'Térreo', 6, 3, null),
      ('EQ2', '07', 'Térreo', 1, 1, 'Eduardo'),
      ('EQ2', '07', 'Térreo', 1, 2, 'Eduardo'),
      ('EQ2', '07', 'Térreo', 1, 3, 'Eduardo'),
      ('EQ2', '07', 'Térreo', 2, 1, 'Eduardo'),
      ('EQ2', '07', 'Térreo', 2, 2, 'Eduardo'),
      ('EQ2', '07', 'Térreo', 2, 3, 'Eduardo'),
      ('EQ2', '07', 'Térreo', 3, 1, 'Eduardo'),
      ('EQ2', '07', 'Térreo', 3, 2, 'Eduardo'),
      ('EQ2', '07', 'Térreo', 3, 3, 'Eduardo'),
      ('EQ2', '07', 'Térreo', 4, 1, 'Eduardo'),
      ('EQ2', '07', 'Térreo', 4, 2, 'Eduardo'),
      ('EQ2', '07', 'Térreo', 4, 3, 'Eduardo'),
      ('EQ2', '07', 'Térreo', 6, 2, null),
      ('EQ2', '07', 'Térreo', 6, 3, null)
    ) as v(unidade, numero, andar, dia, periodo, nome)
  loop
    select id into v_sala from public.salas s
     where s.unidade = r.unidade and lower(s.numero) = lower(r.numero)
       and coalesce(s.andar, '') = r.andar;
    if v_sala is null then continue; end if;

    if r.nome is null then
      if not exists (select 1 from public.salas_ocupacoes o
                      where o.sala_id = v_sala and o.dia_semana = r.dia
                        and o.periodo = r.periodo and o.rotulo = 'Indisponível') then
        insert into public.salas_ocupacoes (sala_id, rotulo, dia_semana, periodo)
        values (v_sala, 'Indisponível', r.dia, r.periodo);
        n_oc := n_oc + 1;
      else
        n_oc_ja := n_oc_ja + 1;
      end if;
    else
      select colaborador_id into v_colab from imp_salas_res where nome = r.nome;
      if v_colab is not null then
        if not exists (select 1 from public.salas_ocupacoes o
                        where o.sala_id = v_sala and o.dia_semana = r.dia
                          and o.periodo = r.periodo and o.colaborador_id = v_colab) then
          insert into public.salas_ocupacoes (sala_id, colaborador_id, dia_semana, periodo)
          values (v_sala, v_colab, r.dia, r.periodo);
          n_oc := n_oc + 1;
        else
          n_oc_ja := n_oc_ja + 1;
        end if;
      else
        if not exists (select 1 from public.salas_ocupacoes o
                        where o.sala_id = v_sala and o.dia_semana = r.dia
                          and o.periodo = r.periodo and o.rotulo = r.nome) then
          insert into public.salas_ocupacoes (sala_id, rotulo, dia_semana, periodo)
          values (v_sala, r.nome, r.dia, r.periodo);
          n_oc := n_oc + 1;
        else
          n_oc_ja := n_oc_ja + 1;
        end if;
      end if;
    end if;
  end loop;

  raise notice 'IMPORTACAO SALAS: % salas novas, % ja existiam | % celulas inseridas, % ja estavam',
    n_salas_novas, n_salas_ja, n_oc, n_oc_ja;
end
$$;

-- ============================================================
-- RELATORIO
-- ============================================================
select r.nome as nome_no_croqui, r.situacao,
       coalesce((select c.nome from public.colaboradores c where c.id = r.colaborador_id), '') as casado_com
  from imp_salas_res r
 order by r.situacao, r.nome;

select (select count(*) from public.salas) as salas_total,
       (select count(*) from public.salas_ocupacoes) as celulas_total;

-- ============================================================
-- FIM DO 13 - abra o modulo Salas e veja a grade viva
-- ============================================================
